import type { FieldGuideCaseInput } from "./field-guide.service";

/**
 * Starter content for the paramedic field guide — short action reminders for
 * common sport-event emergencies. Editable from the dashboard; this seed only
 * applies when data/field-guide.json is missing or empty.
 */
export const SEED_FIELD_GUIDE: FieldGuideCaseInput[] = [
  {
    title: "Cardiac arrest",
    category: "cardiac",
    keywords: ["unresponsive", "no breathing", "no pulse", "collapse", "CPR", "AED"],
    summary: "Unresponsive, not breathing normally — start CPR immediately.",
    signs: ["No response to voice/pain", "No or agonal (gasping) breathing", "No pulse within 10s"],
    actions: [
      "Call for backup + AED immediately",
      "Start compressions: 100–120/min, 5–6 cm deep, full recoil",
      "30:2 with ventilations, minimize pauses",
      "Attach AED as soon as it arrives — follow prompts",
      "Rotate compressors every 2 min",
    ],
    redFlags: ["Any delay to compressions reduces survival ~10% per minute"],
  },
  {
    title: "Heart attack (MI)",
    category: "cardiac",
    keywords: ["chest pain", "pressure", "arm pain", "jaw pain", "sweating", "nausea", "infarct"],
    summary: "Crushing chest pain/pressure, often with sweating and nausea.",
    signs: ["Central chest pressure >15 min", "Radiates to arm/jaw/back", "Pale, sweaty, anxious", "Shortness of breath"],
    actions: [
      "Stop all exertion, sit patient down (W-position)",
      "Call ambulance for transport — this is time-critical",
      "Aspirin 300 mg chewed (if no allergy/bleeding)",
      "Monitor closely — be ready for arrest (AED nearby)",
    ],
    redFlags: ["Loss of consciousness", "Irregular/absent pulse", "BP drop"],
  },
  {
    title: "Stroke",
    category: "neuro",
    keywords: ["face droop", "arm weakness", "speech", "FAST", "confusion", "sudden headache"],
    summary: "FAST: Face droop, Arm weakness, Speech trouble — Time to evacuate.",
    signs: ["Facial droop on one side", "One arm drifts down", "Slurred/strange speech", "Sudden severe headache or vision loss"],
    actions: [
      "Note exact time of symptom onset — critical for thrombolysis",
      "Immediate ambulance transport, no delays on scene",
      "Nothing by mouth (swallowing may be impaired)",
      "Position: slightly elevated head if conscious; recovery position if not",
    ],
    redFlags: ["Decreasing consciousness", "Seizure", "Onset time unknown"],
  },
  {
    title: "Hypoglycemia",
    category: "metabolic",
    keywords: ["diabetic", "low sugar", "shaky", "sweaty", "confused", "glucose"],
    summary: "Diabetic or exhausted athlete: shaky, sweaty, confused — give sugar.",
    signs: ["Trembling, cold sweat", "Confusion, aggression, slurred speech", "Pale skin", "Known diabetic / long race effort"],
    actions: [
      "Conscious & can swallow: 15–20 g fast sugar (gel, juice, cola)",
      "Re-check in 10–15 min, repeat sugar if still symptomatic",
      "Follow with slow carbs (bar, sandwich) once improving",
      "Unconscious: recovery position, NOTHING by mouth, call ambulance (IM glucagon if available)",
    ],
    redFlags: ["Unconsciousness or seizure", "No improvement after second dose"],
  },
  {
    title: "Heat stroke",
    category: "environmental",
    keywords: ["hot", "collapse", "confusion", "no sweating", "core temperature", "hyperthermia"],
    summary: "Hot + confused athlete = emergency. Cool first, transport second.",
    signs: ["Altered mental state (confusion, aggression, collapse)", "Core temp >40°C (rectal if possible)", "Hot skin — sweating may continue in exertional heat stroke"],
    actions: [
      "Move to shade, strip excess clothing",
      "Aggressive cooling NOW: ice-water immersion if available, else ice packs to neck/armpits/groin + douse with water and fan",
      "Cool first, transport second (target <39°C)",
      "Monitor airway and consciousness throughout",
    ],
    redFlags: ["Seizures", "Vomiting with reduced consciousness", "No rapid temperature drop"],
  },
  {
    title: "Heat exhaustion",
    category: "environmental",
    keywords: ["dizzy", "cramps", "nausea", "fatigue", "dehydration", "hot"],
    summary: "Dizzy, nauseous, heavy sweating but mentally intact — rest and cool.",
    signs: ["Heavy sweating, pale", "Dizziness, headache, nausea, cramps", "Normal or mildly elevated mentation — answers correctly"],
    actions: [
      "Stop activity, shade, lie down with legs elevated",
      "Cool with water spray + fanning, cold packs",
      "Oral rehydration with electrolytes if not vomiting",
      "Reassess in 15–30 min before any return to course",
    ],
    redFlags: ["Any confusion → treat as heat stroke", "Persistent vomiting", "Symptoms not improving in 30 min"],
  },
  {
    title: "Anaphylaxis",
    category: "allergy",
    keywords: ["allergic", "swelling", "hives", "wheeze", "bee sting", "epipen"],
    summary: "Rapid allergic reaction with airway/breathing/circulation involvement — adrenaline first.",
    signs: ["Hives + facial/lip swelling", "Wheeze, hoarse voice, stridor", "Hypotension, dizziness, collapse", "Onset minutes after sting/food"],
    actions: [
      "IM adrenaline 0.5 mg anterolateral thigh IMMEDIATELY (EpiPen)",
      "Call ambulance — always transport after adrenaline",
      "Lie flat, legs raised (sitting up only if breathing is hard)",
      "Repeat adrenaline after 5 min if no improvement",
    ],
    redFlags: ["Stridor or silent chest", "Collapse — never stand the patient up suddenly"],
  },
  {
    title: "Asthma attack",
    category: "airway",
    keywords: ["wheeze", "inhaler", "can't breathe", "tight chest", "salbutamol"],
    summary: "Wheezing, struggling to speak — assist with their inhaler, sit upright.",
    signs: ["Wheeze, prolonged exhale", "Speaking in short phrases/words", "Using neck/shoulder muscles to breathe"],
    actions: [
      "Sit upright, stay calm and coach slow breathing",
      "4–10 puffs salbutamol via spacer, repeat every 10–15 min as needed",
      "No improvement after 10 puffs → ambulance",
      "Monitor for exhaustion — quieting wheeze can be deterioration",
    ],
    redFlags: ["Silent chest", "Cyanosis (blue lips)", "Exhaustion or confusion"],
  },
  {
    title: "Seizure",
    category: "neuro",
    keywords: ["convulsion", "epilepsy", "fitting", "shaking", "postictal"],
    summary: "Protect from injury, time the seizure, recovery position after.",
    signs: ["Tonic-clonic shaking, unresponsive", "Possible tongue biting / incontinence", "Confused (postictal) afterwards"],
    actions: [
      "Time it from the start; clear hard objects away, pad the head",
      "Do NOT restrain, nothing in the mouth",
      "When jerking stops: airway check + recovery position",
      "Stay until fully reoriented; check glucose if possible",
    ],
    redFlags: [">5 min or repeated seizures (status) → ambulance + escalate", "First-ever seizure", "Seizure after head injury or in water"],
  },
  {
    title: "Severe bleeding",
    category: "trauma",
    keywords: ["hemorrhage", "bleeding", "laceration", "tourniquet", "pressure"],
    summary: "Direct pressure first, tourniquet for limb bleeds that won't stop.",
    signs: ["Visible heavy/spurting bleed", "Soaked dressings", "Pale, fast pulse → shock developing"],
    actions: [
      "Gloves on; firm direct pressure with dressing",
      "Bleeding through? Add a second dressing on top, press harder",
      "Uncontrollable limb bleed: tourniquet 5–7 cm above the wound, note the time",
      "Treat for shock: lie flat, keep warm; urgent transport",
    ],
    redFlags: ["Pulsatile/arterial bleeding", "Signs of shock", "Junctional bleeds (groin/axilla) — pack and hold"],
  },
  {
    title: "Fractured femur",
    category: "trauma",
    keywords: ["thigh", "leg fracture", "deformity", "traction", "fall", "crash"],
    summary: "Shortened, rotated, very painful thigh — splint, treat for shock, transport.",
    signs: ["Severe thigh pain, unable to weight-bear", "Leg shortened/rotated, thigh swelling", "High-energy mechanism (bike crash, fall)"],
    actions: [
      "Don't move until splinted; check pulse/sensation below injury",
      "Traction splint if trained & available, else immobilize to the other leg with padding",
      "Treat for shock — femur can lose 1–1.5 L blood internally",
      "Analgesia per protocol; ambulance transport",
    ],
    redFlags: ["No distal pulse", "Open fracture", "Shock signs"],
  },
  {
    title: "Ankle / lower limb injury",
    category: "trauma",
    keywords: ["sprain", "ankle", "twist", "swelling", "RICE", "ottawa"],
    summary: "Twisted ankle: RICE; suspect fracture if bony tenderness or can't walk 4 steps.",
    signs: ["Swelling/bruising around the joint", "Pain on bony landmarks (malleoli, 5th metatarsal)", "Unable to take 4 steps"],
    actions: [
      "Rest, Ice (max 20 min), Compression bandage, Elevation",
      "Bony tenderness or can't weight-bear → immobilize, treat as fracture",
      "Check pulse/sensation distal to the injury",
      "Arrange transport off course — no hopping kilometres",
    ],
    redFlags: ["Obvious deformity", "Numb/cold foot", "Open wound over the joint"],
  },
  {
    title: "Head injury / concussion",
    category: "trauma",
    keywords: ["concussion", "head", "fall", "confused", "vomiting", "LOC"],
    summary: "Any knocked head with confusion or LOC comes off the course — period.",
    signs: ["Dazed, slow answers, repeats questions", "Headache, nausea, balance problems", "Brief loss of consciousness"],
    actions: [
      "Remove from activity immediately — no same-day return",
      "Assess responsiveness (AVPU) and reassess every few minutes",
      "Suspect neck injury with high-energy mechanism — keep head still",
      "Worsening symptoms → ambulance for CT",
    ],
    redFlags: ["Repeated vomiting", "Worsening headache or drowsiness", "Unequal pupils", "Seizure", "Blood/fluid from ears/nose"],
  },
  {
    title: "Spinal injury (suspected)",
    category: "trauma",
    keywords: ["neck", "back", "fall from height", "numbness", "tingling", "immobilize"],
    summary: "High-energy mechanism + neck/back pain or neuro signs — don't move them.",
    signs: ["Midline neck/back pain or tenderness", "Numbness, tingling, weakness in limbs", "High-risk mechanism (high-speed crash, fall)"],
    actions: [
      "Tell the patient to keep still; hold head in neutral manual stabilization",
      "Move only for airway problems or scene danger (log-roll with help)",
      "Keep warm, monitor breathing",
      "Ambulance with immobilization equipment",
    ],
    redFlags: ["Any neuro deficit", "Altered consciousness — airway takes priority over the spine"],
  },
  {
    title: "Hyponatremia (overhydration)",
    category: "metabolic",
    keywords: ["too much water", "bloated", "confusion", "endurance", "sodium", "EAH"],
    summary: "Endurance athlete who drank lots of plain water: bloated, confused — do NOT give more fluids.",
    signs: ["High plain-water intake during long events", "Bloating, puffy hands/face, weight gain", "Headache, nausea, confusion — can mimic dehydration"],
    actions: [
      "STOP all hypotonic fluids — no water, no sports drink",
      "Mild + alert: salty snacks, observe",
      "Confusion/vomiting → urgent transport (needs hypertonic saline)",
      "Document fluid intake history for hospital",
    ],
    redFlags: ["Confusion or seizure", "Treating as dehydration and giving fluids makes it fatal"],
  },
  {
    title: "Hypothermia",
    category: "environmental",
    keywords: ["cold", "shivering", "wet", "mountain", "rewarming"],
    summary: "Cold, wet, slowing down: insulate from the ground, rewarm gently, handle gently.",
    signs: ["Shivering (stops when severe)", "Slow, clumsy, withdrawn, slurred", "Cold exposure: wet clothing, wind, exhaustion"],
    actions: [
      "Shelter from wind/rain; remove wet clothing",
      "Insulate from ground; wrap including head (hypothermia wrap)",
      "Conscious + shivering: warm sweet drinks, calorie intake",
      "Severe (no shivering, drowsy): handle very gently, no standing/walking, urgent evacuation",
    ],
    redFlags: ["Stopped shivering", "Decreased consciousness", "Rough handling can trigger arrest"],
  },
  {
    title: "Shock",
    category: "cardiac",
    keywords: ["pale", "fast pulse", "low blood pressure", "clammy", "bleeding"],
    summary: "Pale, clammy, fast weak pulse — find and treat the cause, lie flat, keep warm.",
    signs: ["Pale/grey, cold, clammy skin", "Fast weak pulse, fast breathing", "Anxiety → drowsiness as it worsens"],
    actions: [
      "Lie flat, elevate legs (unless breathing problems/chest injury)",
      "Control any external bleeding",
      "Keep warm, nothing by mouth",
      "Urgent transport — monitor consciousness and pulse continuously",
    ],
    redFlags: ["Falling consciousness", "Hidden bleeds: abdomen, pelvis, femur"],
  },
  {
    title: "Choking",
    category: "airway",
    keywords: ["airway", "obstruction", "can't speak", "universal sign", "heimlich"],
    summary: "Can't speak or cough: 5 back blows, 5 abdominal thrusts, repeat.",
    signs: ["Clutching throat, unable to speak/cough", "Silent attempts to cough, panic", "Cyanosis developing"],
    actions: [
      "Effective cough → encourage coughing, watch",
      "Ineffective: 5 sharp back blows between shoulder blades",
      "Then 5 abdominal thrusts; alternate 5-and-5",
      "Unconscious → start CPR, look in mouth before breaths",
    ],
    redFlags: ["Loss of consciousness", "Persistent obstruction after thrusts"],
  },
  {
    title: "Dehydration",
    category: "metabolic",
    keywords: ["thirst", "dry mouth", "dark urine", "dizzy", "fatigue", "headache", "cramps", "fluid"],
    summary: "Thirst, dark urine, fatigue and dizziness — rehydrate gradually.",
    signs: ["Dry mouth/lips, intense thirst", "Dark, scant urine", "Dizziness, headache, fatigue", "Fast pulse"],
    actions: [
      "Move to shade, stop activity, sit/lie down",
      "Sip oral rehydration / electrolyte fluids gradually",
      "Cool the skin; loosen clothing",
      "Recheck in 15–20 min; escalate if not improving",
    ],
    redFlags: ["Confusion or fainting", "No urine output", "Vomiting everything back up"],
  },
  {
    title: "Exercise-associated muscle cramps",
    category: "metabolic",
    keywords: ["cramp", "muscle cramp", "calf", "spasm", "charley horse", "twinge", "tight muscle"],
    summary: "Sudden painful muscle spasm — stretch, hydrate, replace salts.",
    signs: ["Sudden, visible/palpable muscle knot", "Severe localized pain", "Often calves/hamstrings/quads"],
    actions: [
      "Gently stretch and hold the affected muscle",
      "Light massage once the spasm eases",
      "Rehydrate with electrolyte fluids",
      "Rest before returning to activity",
    ],
    redFlags: ["Whole-body cramping", "Dark 'cola' urine (rhabdo)", "Cramps with confusion (check sodium/heat)"],
  },
  {
    title: "Fainting (vasovagal syncope)",
    category: "neuro",
    keywords: ["faint", "passed out", "collapse", "lightheaded", "dizzy", "blacked out", "pale", "syncope"],
    summary: "Brief LOC with quick recovery — lay flat, raise the legs.",
    signs: ["Sudden brief collapse", "Pale, sweaty, slow pulse beforehand", "Rapid recovery once supine"],
    actions: [
      "Lay flat, raise legs ~30 cm",
      "Loosen tight clothing, ensure fresh air",
      "Keep down until fully recovered, then sit slowly",
      "Give fluids once alert; find/treat the cause",
    ],
    redFlags: ["No recovery within 1–2 min", "Chest pain or palpitations before", "Injury from the fall / head strike"],
  },
  {
    title: "Hyperventilation / panic attack",
    category: "airway",
    keywords: ["hyperventilate", "panic", "anxiety", "tingling", "rapid breathing", "can't breathe", "pins and needles"],
    summary: "Fast breathing, tingling, anxiety — calm and slow the breathing.",
    signs: ["Very rapid, shallow breathing", "Tingling in hands/around mouth", "Chest tightness, fear, dizziness"],
    actions: [
      "Reassure calmly; move away from the crowd",
      "Coach slow breathing (in 4s, out 6s)",
      "Rule out asthma/cardiac/allergic cause first",
      "Stay until breathing and pulse settle",
    ],
    redFlags: ["Known asthmatic or cardiac history", "Blue lips, true shortness of breath", "Doesn't settle with coaching"],
  },
  {
    title: "Nosebleed (epistaxis)",
    category: "trauma",
    keywords: ["nosebleed", "nose bleed", "epistaxis", "bleeding nose", "blood from nose"],
    summary: "Pinch the soft nose, lean forward, 10–15 min.",
    signs: ["Bleeding from one/both nostrils", "Often after a knock or in dry heat"],
    actions: [
      "Sit up, head tipped slightly forward",
      "Pinch the soft part of the nose firmly for 10–15 min",
      "Breathe through the mouth; don't release early",
      "Apply a cold pack to the bridge of the nose",
    ],
    redFlags: ["Bleeding >20–30 min despite pressure", "Heavy bleed after head/face trauma", "On blood thinners"],
  },
  {
    title: "Sprain / strain",
    category: "trauma",
    keywords: ["sprain", "strain", "twisted", "rolled ankle", "pulled muscle", "swelling", "joint", "wrist", "knee"],
    summary: "Joint/muscle injury — rest, ice, compression, elevation.",
    signs: ["Pain, swelling, bruising around a joint/muscle", "Reduced movement", "Tender to touch"],
    actions: [
      "Rest — stop activity, protect the limb",
      "Ice 15–20 min (cloth between ice and skin)",
      "Compress with a bandage (not too tight)",
      "Elevate above heart level; review weight-bearing",
    ],
    redFlags: ["Obvious deformity (suspect fracture)", "Cannot bear weight / use the limb", "Numb, cold or blue beyond the injury"],
  },
  {
    title: "Dislocated shoulder",
    category: "trauma",
    keywords: ["dislocation", "shoulder", "out of socket", "arm stuck", "deformity", "joint"],
    summary: "Arm held away from body, squared-off shoulder — immobilize, don't force.",
    signs: ["Severe shoulder pain after fall/throw", "Arm held slightly out, resists movement", "Squared-off / flat shoulder shape"],
    actions: [
      "Support the arm in the position found",
      "Do NOT attempt to relocate it in the field",
      "Pad and sling/immobilize; cold pack for pain",
      "Arrange transport for reduction + X-ray",
    ],
    redFlags: ["Numb/cold hand, weak pulse at wrist", "Suspected fracture too", "Repeated dislocations"],
  },
  {
    title: "Eye injury / foreign body",
    category: "trauma",
    keywords: ["eye", "foreign body", "grit", "dust", "scratch", "vision", "chemical", "splash"],
    summary: "Irritation or trauma to the eye — flush, don't rub, cover.",
    signs: ["Pain, watering, redness", "Sensation of something in the eye", "Blurred vision, light sensitivity"],
    actions: [
      "Loose grit/chemical: flush with clean water/saline 10+ min",
      "Don't rub; don't remove an embedded object",
      "Cover both eyes lightly to rest movement",
      "Refer for chemical, penetrating, or vision-loss injuries",
    ],
    redFlags: ["Penetrating object — leave in place", "Vision loss", "Chemical splash"],
  },
  {
    title: "Sunburn",
    category: "environmental",
    keywords: ["sunburn", "burn", "red skin", "uv", "blisters", "sun"],
    summary: "Red, hot, sore skin from sun — cool, hydrate, cover.",
    signs: ["Red, warm, tender skin", "Possible blistering", "Often with mild heat illness"],
    actions: [
      "Get out of the sun, cool the skin (cool water/compress)",
      "Hydrate; give simple analgesia if appropriate",
      "Cover with light clothing; don't burst blisters",
      "Aftersun / aloe for comfort",
    ],
    redFlags: ["Widespread blistering", "Signs of heat exhaustion/stroke", "Fever or feeling very unwell"],
  },
  {
    title: "Insect sting / bite",
    category: "allergy",
    keywords: ["sting", "bite", "bee", "wasp", "hornet", "swelling", "itch", "insect"],
    summary: "Local pain/swelling — remove sting, cool; watch for allergy.",
    signs: ["Sharp pain then local swelling/redness", "Itching at the site"],
    actions: [
      "Scrape out a bee sting (don't squeeze the sac)",
      "Wash the area; apply a cold pack",
      "Antihistamine for itch if available/appropriate",
      "Watch 15–30 min for spreading/allergic signs",
    ],
    redFlags: ["Facial/lip/tongue swelling or wheeze → treat as anaphylaxis", "Stung in the mouth/throat", "Many stings"],
  },
  {
    title: "Diabetic high blood sugar (hyperglycemia)",
    category: "metabolic",
    keywords: ["hyperglycemia", "high blood sugar", "diabetic", "thirsty", "frequent urination", "drowsy", "fruity breath", "dka"],
    summary: "Thirst, drowsiness, fruity breath in a diabetic — needs medical care.",
    signs: ["Very thirsty, frequent urination", "Drowsy/confused, warm dry skin", "Deep breathing, fruity-smelling breath"],
    actions: [
      "Do NOT give sugar (opposite of a hypo)",
      "Encourage water if alert and able to swallow",
      "Let them take their own insulin if they can",
      "Arrange urgent transport — can deteriorate fast",
    ],
    redFlags: ["Drowsy/unresponsive", "Vomiting", "Deep rapid breathing (DKA)"],
  },
  {
    title: "Abdominal pain / side stitch",
    category: "other",
    keywords: ["stomach", "abdominal", "stitch", "side pain", "cramp", "belly", "gut"],
    summary: "Most stitches are benign — but screen for serious abdominal pain.",
    signs: ["Stitch: sharp upper-side pain on exertion, eases with rest", "Serious: constant/worsening pain, tenderness, vomiting"],
    actions: [
      "Stitch: slow down, deep breathe, stretch the side, press the area",
      "Rest and rehydrate",
      "Serious pain: keep nil by mouth, position of comfort",
      "Escalate persistent, severe, or localized pain",
    ],
    redFlags: ["Rigid/very tender abdomen", "Pain with fainting or blood", "Pain after abdominal trauma"],
  },
  {
    title: "Frostbite / cold injury",
    category: "environmental",
    keywords: ["frostbite", "cold", "numb", "white fingers", "frozen", "extremities", "chilblains"],
    summary: "Numb, white/waxy skin on extremities — rewarm gently, don't rub.",
    signs: ["Numb, hard, white/waxy skin", "Fingers, toes, ears, nose", "Pain/blisters on rewarming"],
    actions: [
      "Get into shelter/warmth; remove wet/tight items",
      "Rewarm gently with body heat or warm (not hot) water",
      "Do NOT rub the area or use direct heat",
      "Don't rewarm if refreezing is possible; protect and transport",
    ],
    redFlags: ["Blisters or blackened skin", "Whole-body cold (hypothermia)", "Cannot keep the part thawed"],
  },
  {
    title: "Knocked-out tooth (dental)",
    category: "trauma",
    keywords: ["tooth", "dental", "knocked out", "mouth", "avulsed", "broken tooth", "lip"],
    summary: "Handle by the crown, keep moist, see a dentist fast.",
    signs: ["Tooth fully out of socket after impact", "Bleeding gum / lip injury"],
    actions: [
      "Hold the tooth by the crown, never the root",
      "If clean, reinsert gently; otherwise store in milk/saliva",
      "Bite on gauze to control bleeding",
      "Seek dental care within ~30–60 min for best result",
    ],
    redFlags: ["Suspected jaw fracture", "Inhaled/swallowed tooth", "Heavy uncontrolled bleeding"],
  },
  {
    title: "Minor wound / laceration",
    category: "trauma",
    keywords: ["cut", "graze", "laceration", "wound", "abrasion", "scrape", "bleeding", "road rash"],
    summary: "Clean, control bleeding, dress — decide if it needs closure.",
    signs: ["Break in the skin with minor bleeding", "Grit/debris in grazes"],
    actions: [
      "Direct pressure to stop bleeding",
      "Clean with water/saline once bleeding controlled",
      "Cover with a clean non-stick dressing",
      "Refer for stitches if deep, gaping, or over a joint",
    ],
    redFlags: ["Spurting/uncontrolled bleeding → treat as severe bleeding", "Deep wound to hand/face/joint", "Signs of infection later"],
  },
];
