ALTER TABLE users
  ADD COLUMN IF NOT EXISTS email      TEXT,
  ADD COLUMN IF NOT EXISTS phone      TEXT,
  ADD COLUMN IF NOT EXISTS role       TEXT NOT NULL DEFAULT 'paramedic',
  ADD COLUMN IF NOT EXISTS unit       TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS status     TEXT NOT NULL DEFAULT 'active',
  ADD COLUMN IF NOT EXISTS joined     DATE NOT NULL DEFAULT CURRENT_DATE;
